
import Navbar from "@/components/navBar/navBar";
import ReservaProvider from "@/context/reservaContenxt";
import 'antd/dist/reset.css'; // Versión moderna (Next.js recomienda reset.css)
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
//import "./globals.css";
 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      /*  className={`${geistSans.variable} ${geistMono.variable} antialiased`}*/
      >
        <ReservaProvider>
        <Navbar/>
        {children}
        </ReservaProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
